[B001-C0005] Create a pre-action to merge the dev branch to the main branch - patch 1.
Deck-Link: https://github.com/hoss-java//home/hossein/github-java/EventManagementApp/blob/main/DECK.md#001-0005
Change-Id: I1f7feb27339cda88b1dee4279098725dd0b7c47f

diff --git a/.github/workflows/auto-merge-changes.yml b/.github/workflows/auto-merge-changes.yml
--- a/.github/workflows/auto-merge-changes.yml
+++ b/.github/workflows/auto-merge-changes.yml
@@ -23,9 +23,13 @@ jobs:
         run: |
           SOURCE_BRANCH=develop
           TARGET_BRANCH=main
-          FILES_TO_CHECK=$(grep -v '^\s*#' /.gitautomarge | awk '{print $1}')
-          echo "FILES_TO_CHECK=${FILES_TO_CHECK}" >> $GITHUB_ENV
-
+          if [[ -f .gitautomarge ]]; then
+            FILES_TO_CHECK=$(grep -v '^\s*#' .gitautomarge | awk '{print $1}')
+            echo "FILES_TO_CHECK=${FILES_TO_CHECK}" >> $GITHUB_ENV
+          else
+            echo "File list not found!"
+            exit 1
+          fi
       # Step 4: Check for changes in the specified files
       - name: Auto-check for changes
         id: check-changes
