[B001-C0008] Automate running tests - github action - try 5.
Deck-Link: https://github.com/hoss-java//home/hossein/github-java/EventManagementApp/blob/main/DECK.md#001-0008
Change-Id: I5f74b0bbe1e81992224c337833cff877c5aafaa2

diff --git a/.github/workflows/main-merge-changes.yml b/.github/workflows/main-merge-changes.yml
--- a/.github/workflows/main-merge-changes.yml
+++ b/.github/workflows/main-merge-changes.yml
@@ -102,9 +102,14 @@ jobs:
       - name: Run Tests
         if: env.file_changed == 'true'
         run: |
-          set -x
-          mvn -f EventManApp test  # Use Maven command directly
-          mvn -f EventManApp clean  # Use Maven command directly
+          output=$(mvn -f EventManApp test)  # Run tests
+          TEST_RESULT=$?  # Capture test result
+          output+=$(mvn -f EventManApp clean)  # Clean up after tests
+        
+          if [ $TEST_RESULT -ne 0 ]; then
+            echo "$output"
+            exit 1  # Fail the step if tests did not pass
+          fi
 
       # Step 8: Copy and Push Changes
       - name: Copy and Push Changes
